packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@whiskeysockets/baileys"
  - "@prisma/client"
  - "@prisma/engines"
  - "esbuild"
  - "msgpackr-extract"
  - "protobufjs"
  - "prisma"
  - "sharp"
