import {
  AreaChart,
  Bot,
  CalendarDays,
  ContactRound,
  CreditCard,
  Database,
  FlaskConical,
  Gauge,
  Inbox,
  Megaphone,
  Package,
  PanelTop,
  Settings,
  ShoppingBag,
  Sparkles,
  UsersRound,
  Workflow
} from "lucide-react";

export const navigationItems = [
  { title: "Overview", href: "/dashboard", icon: AreaChart },
  { title: "Simulator", href: "/simulator", icon: FlaskConical },
  { title: "Inbox", href: "/inbox", icon: Inbox },
  { title: "Customers", href: "/customers", icon: ContactRound },
  { title: "Leads CRM", href: "/leads", icon: Workflow },
  { title: "AI Assistant", href: "/ai-assistant", icon: Sparkles },
  { title: "AI Agents", href: "/ai-agents", icon: Bot },
  { title: "Knowledge Base", href: "/knowledge-base", icon: Database },
  { title: "Chatbot Builder", href: "/chatbot-builder", icon: Bot },
  { title: "Campaigns", href: "/campaigns", icon: Megaphone },
  { title: "Products", href: "/products", icon: Package },
  { title: "Orders", href: "/orders", icon: ShoppingBag },
  { title: "Appointments", href: "/appointments", icon: CalendarDays },
  { title: "Analytics", href: "/analytics", icon: AreaChart },
  { title: "Team", href: "/team", icon: UsersRound },
  { title: "Settings", href: "/settings", icon: Settings },
  { title: "Billing", href: "/billing", icon: CreditCard },
  { title: "Usage", href: "/usage", icon: Gauge },
  { title: "Legacy workflows", href: "/workflows", icon: PanelTop, hidden: true },
  { title: "Legacy contacts", href: "/contacts", icon: ContactRound, hidden: true },
  { title: "Legacy CRM", href: "/crm", icon: Workflow, hidden: true },
  { title: "Legacy conversations", href: "/conversations", icon: Inbox, hidden: true },
  { title: "Legacy chatbots", href: "/chatbots", icon: Bot, hidden: true }
] as const;
